### ISSUE TITLE
Crashing in 1.21.3

### ISSUE THREAD

**Issue by brunorsch** [FractalingCoder/vanilla_constructs#1]
Hey friend, looks like the mod is not working in 1.21.3, take a look at the error I got:

```java
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanillaconstructs' at 'net.fractalcoder.vanillaconstructs.VanillaConstructs'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at knot//net.minecraft.class_310.<init>(class_310.java:482)
at knot//net.minecraft.client.main.Main.main(Main.java:248)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1832
at knot//net.fractalcoder.vanillaconstructs.VanillaConstructs.onInitialize(VanillaConstructs.java:59)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1832
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 8 more
```

I can help with more info if you need it, just ask!

**Comment by FractalingCoder** [comment]
Ok so it looks like 1.21.3 changes A LOT of things, so give a little bit of time to fix all of them

**Comment by brunorsch** [comment]
No problem mate, I'm just here to let you know! 🫡

**Comment by FractalingCoder** [comment]
Alright I've fixed all the issues and have uploaded a new version of the mod!
